---
title: "homework_05"
author: "Lamija Semic"
date: "`(2/12/25)`"
output: html_document
---

**1**

``` {r}
random_value <- runif(1, min=3, max=10)
n_dims <- as.integer(random_value)
print(n_dims)

my_vec <- 1:n_dims^2

sample(x=my_vec)


m <- matrix(data=my_vec,nrow=n_dims)
print(m)

transposed_matrix <- t(m)
print(transposed_matrix)

# switches order of columns and rows

rowSums(m)

rowMeans(m)

eigen(m)

# $values: these numbers are all eigen values of the matrix.

# $vectors: each column of these numbers are eigen vectors, that correspond with the eigen values.

#value
typeof(1.611684e+01)

#vector
typeof(-0.4645473)


``` 

**2**

``` {r}
my_matrix <- matrix(runif(16), nrow=4, ncol=4)
print(my_matrix)


my_logical <- runif(100) 
my_logical <- sample(c(TRUE, FALSE), 100, replace = TRUE)
print(my_logical)


my_letters <- sample(letters, 26)
print(my_letters)


new_list <- c(my_matrix[2,2], my_logical[2], my_letters[1])
print(new_list)

typeof(my_matrix[2,2])
typeof(my_logical[2])
typeof(my_logical[2])

typeof(new_list)

```


**3**

``` {r}

my_unis <- runif(26, min=0, max=10)
print(my_unis)

my_letters <- sample(LETTERS, 26)
print(my_letters)

data_frame <- matrix(c(my_unis, my_letters), nrow=26, ncol=2)
print(data_frame)  

data_frame[sample(1:nrow(data_frame), 4), 1] <- NA
which(!complete.cases(data_frame))

str(data_frame)

my_letters_sorted <- sort(my_letters)
print(my_letters_sorted)

data_frame <- matrix(c(my_unis, my_letters_sorted), nrow=26, ncol=2)
print(data_frame)  

```
